### ISSUE TITLE
Currently not building due to template issue?

### ISSUE THREAD

**Issue by kdyson** [openforis/collect-earth-online-doc#6]
Error in current build of documentation in ReadtheDocs (https://readthedocs.org/projects/collect-earth-online-doc/builds/22978680/) relates to pydata_sphinx_theme.

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/collect-earth-online-doc/envs/kd-changes/lib/python3.11/site-packages/sphinx/events.py", line 96, in emit
    results.append(listener.handler(self.app, *args))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/collect-earth-online-doc/envs/kd-changes/lib/python3.11/site-packages/pydata_sphinx_theme/__init__.py", line 235, in update_and_remove_templates
    context[section] = list(filter(_remove_empty_templates, context[section]))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/collect-earth-online-doc/envs/kd-changes/lib/python3.11/site-packages/pydata_sphinx_theme/__init__.py", line 230, in _remove_empty_templates
    rendered = app.builder.templates.render(tname, context)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/collect-earth-online-doc/envs/kd-changes/lib/python3.11/site-packages/readthedocs_ext/readthedocs.py", line 181, in rtd_render
    content = old_render(template, render_context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/collect-earth-online-doc/envs/kd-changes/lib/python3.11/site-packages/sphinx/jinja2glue.py", line 196, in render
    return self.environment.get_template(template).render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/collect-earth-online-doc/envs/kd-changes/lib/python3.11/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/collect-earth-online-doc/envs/kd-changes/lib/python3.11/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/collect-earth-online-doc/envs/kd-changes/lib/python3.11/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/collect-earth-online-doc/envs/kd-changes/lib/python3.11/site-packages/sphinx/jinja2glue.py", line 217, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: map.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/collect-earth-online-doc/envs/kd-changes/lib/python3.11/site-packages/sphinx/cmd/build.py", line 290, in build_main
    app.build(args.force_all, args.filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/collect-earth-online-doc/envs/kd-changes/lib/python3.11/site-packages/sphinx/application.py", line 351, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/collect-earth-online-doc/envs/kd-changes/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 290, in build_update
    self.build(to_build,
  File "/home/docs/checkouts/readthedocs.org/user_builds/collect-earth-online-doc/envs/kd-changes/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 360, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/docs/checkouts/readthedocs.org/user_builds/collect-earth-online-doc/envs/kd-changes/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 567, in write
    self._write_serial(sorted(docnames))
  File "/home/docs/checkouts/readthedocs.org/user_builds/collect-earth-online-doc/envs/kd-changes/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 577, in _write_serial
    self.write_doc(docname, doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/collect-earth-online-doc/envs/kd-changes/lib/python3.11/site-packages/sphinx/builders/html/__init__.py", line 675, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/collect-earth-online-doc/envs/kd-changes/lib/python3.11/site-packages/sphinx/builders/html/__init__.py", line 1076, in handle_page
    newtmpl = self.app.emit_firstresult('html-page-context', pagename,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/collect-earth-online-doc/envs/kd-changes/lib/python3.11/site-packages/sphinx/application.py", line 487, in emit_firstresult
    return self.events.emit_firstresult(event, *args,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/collect-earth-online-doc/envs/kd-changes/lib/python3.11/site-packages/sphinx/events.py", line 117, in emit_firstresult
    for result in self.emit(name, *args, allowed_exceptions=allowed_exceptions):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/collect-earth-online-doc/envs/kd-changes/lib/python3.11/site-packages/sphinx/events.py", line 107, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <function update_and_remove_templates at 0x7fa566b38720> for event 'html-page-context' threw an exception (exception: map.html)

Extension error (pydata_sphinx_theme):
Handler <function update_and_remove_templates at 0x7fa566b38720> for event 'html-page-context' threw an exception (exception: map.html)

**Comment by kdyson** [comment]
this was because there are files missing that are present in SEPAL template. add them back in when time allows.
